name: Run DVC pipeline
on:
  push:
    branches:
      - dev/*

jobs:
  pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    env:
      WORKFLOW_IMAGE: europe-west2-docker.pkg.dev/gothic-album-364814/pauljs-io/mlops-dvc

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: "auth"
        name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v0.8.3"
        with:
          workload_identity_provider: ${{secrets.WI_PROVIDER}}
          service_account: ${{secrets.GSA_ARGO_WF}}

      - name: Authorize access to GKE cluster
        id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v0.8.2"
        with:
          cluster_name: "k8s-cluster"
          location: "europe-west2-a"

      - name: Authenticate Docker
        run: gcloud auth configure-docker --quiet

      - name: Setup Docker BuildKit
        uses: docker/setup-buildx-action@v2

      - name: Build & Publish Workflow Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          target: dvc
          push: true
          tags: ${WORKFLOW_IMAGE}:${{ github.sha }}
          cache-from: type=registry,ref=${WORKFLOW_IMAGE}:buildcache
          cache-to: type=registry,ref=${WORKFLOW_IMAGE}:buildcache,mode=max

      - name: Create Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "ci/requirements.txt"

      - name: Configure Python Environment
        run: pip install -r ci/requirements.txt

      - name: Submit Argo Workflow
        run: ci/main.py --target ml_pipelines/ci/dvc.yaml
