name: Run DVC pipeline
on:
  pull_request:
    types:
      - ready_for_review
jobs:
  dvc-status:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check DVC config is up to date
        run: dvc status -q
