name: DVC status check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  dvc-status:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v0.8.3"
        with:
          workload_identity_provider: ${{secrets.WI_PROVIDER}}
          service_account: ${{secrets.GSA_DVC_REMOTE}}

      - name: Create Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements-dvc.txt"

      - name: Configure Python Environment
        run: pip install -r requirements-dvc.txt

      - name: Check for missing changes in DVC workspace
        run: |
          dvc pull --run-cache
          dvc status
          dvc status -q
